accounts/urls.py
# accounts/urls.py
# LogoutView는 django.contrib.auth에서 제공하는 기능이라 따로 만들 필요가 없다.
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'
urlpatterns = [
    path ('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path ('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path ('signup/', views.signup, name='signup'),
]

goods/urls.py
# goods/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.mainpage), # mainpage 연결
    path('company/', views.company), # goods/views.py 파일의 company라는 함수를 /company라는 링크에 연결
]

promote/urls.py
# promote/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index), # /promote 로 promote/views.py의 index() 연결
    path('<int:content_id>/', views.detail, name='detail'), # /promote/content_id 로 views.py의 detail() 연결, name을 작성하여 .html url 연동에서 하드코딩 방지
    path('comment/create/<int:content_id>/', views.comment_create, name='comment_create'),
    path('comment/update/<int:comment_id>/', views.comment_update, name='comment_update'),
    path('comment/delete/<int:comment_id>/', views.comment_delete, name='comment_delete'),
]

promote_site/urls.py
# promote_site/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('promote/', include('promote.urls')), # http://127.0.0.1:8000/promote/ 로 promote/urls.py 파일 연결
    path('', include('goods.urls')),
    path('accounts/', include('accounts.urls')),
]

accounts/models.py
from django.db import models

# Create your models here.

promote/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class MainContent(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    pub_date = models.DateTimeField('date_published')
    
    def __str__(self):
        return self.title
    
class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content_list = models.ForeignKey(MainContent, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField(auto_now_add=True)
    modify_date = models.DateTimeField(auto_now=True)

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class SignupForm(UserCreationForm):
    email = forms.EmailField()
    class Meta:
        model = User
        fields = ("username", "password1", "password2", "email")

promote/forms.py
from .models import Comment
from django import forms

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)

accounts/views.py
from django.contrib.auth import login
from django.shortcuts import render, redirect
from accounts.forms import SignupForm

# Create your views here.

def signup(request):
    if request.method == "POST":
        form = SignupForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('/')
    else:
        form = SignupForm()
    return render(request, 'accounts/signup.html', {'form':form})

goods/views.py
from django.shortcuts import render

# Create your views here.
def mainpage(request):
    return render(request, 'goods/mainpage.html')

def company(request):
    return render(request, 'goods/company_info.html')

promote/views.py
# promote/views.py
from django.core.exceptions import PermissionDenied
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth.decorators import login_required
# get_object_or_404 : 404 오류 발생시 연결해줄 view (사용 안할시 DoesNotExist 오류 뜸, 사용시 Page not found(404) 뜨게 해줌)
# render : content_list 데이터를 promote/content_list.html 파일에 적용 후 HTML 리턴
from .models import MainContent, Comment
from .forms import CommentForm

# Create your views here.

def index(request):
    content_list = MainContent.objects.order_by('-pub_date') # 역순 정렬(가장 최신 콘텐츠를 상단에 노출)
    context = {'content_list': content_list}
    return render(request, 'promote/content_list.html', context)

def detail(request, content_id):
    content_list = get_object_or_404(MainContent, pk=content_id)
    # content_list = MainContent.objects.get(id=content_id) # content_id 를 가져옴
    context = {'content_list': content_list}
    return render(request, 'promote/content_detail.html', context)

@login_required(login_url='accounts:login')
def comment_create(request, content_id):
    content_list = get_object_or_404(MainContent, pk=content_id)
    
    if request.method=='POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment=form.save(commit=False)
            comment.content_list=content_list
            comment.author=request.user
            comment.save()
            return redirect('detail', content_id=content_list.id)
    else:
        form = CommentForm()
    context={'content_list' : content_list, 'form': form}
    return render(request, 'promote/content_detail.html', context)

@login_required(login_url='accounts:login')
def comment_update(request, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    
    if request.user != comment.author:
        raise PermissionDenied
    
    if request.method == 'POST':
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.save()
            return redirect('detail', content_id=comment.content_list.id)
    else:
        form = CommentForm(instance=comment)

    context = {'comment': comment, 'form': form}
    return render(request, 'promote/comment_form.html', context)

@login_required(login_url='accounts:login')
def comment_delete(request, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    
    if request.user != comment.author:
        raise PermissionDenied
    else:
        comment.delete()
    return redirect('detail', content_id=comment.content_list.id)

templates/accounts/login.html
{% extends "base.html" %}
{% block content %}

{% if form.errors %}
<p>아이디 또는 비밀번호가 틀립니다. 다시 시도해주세요.</p>
{% endif %}

<form method="post" action="{% url 'accounts:login' %}">
    {% csrf_token %}
    <table>
        <tr>
            <td>{{ form.username.label_tag }}</td>
            <td>{{ form.username }}</td>
        </tr>
        <tr>
            <td>{{ form.password.label_tag }}</td>
            <td>{{ form.password }}</td>
        </tr>
    </table>
    <input type="submit" value="로그인">
</form>
<a href = "{% url 'accounts:signup' %}">signup 화면으로 이동</a>
{% endblock %}

templates/accounts/signup.html
{% extends "base.html" %}
{% block content %}
<!-- 
{% if form.errors %}
<p>아이디 또는 비밀번호가 틀립니다. 다시 시도해주세요.</p>
{% endif %} -->

<form method="post" action="{% url 'accounts:signup' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <!-- <table>
        <tr>
            <td>{{ form.username.label_tag }} {{ form.username }} 150자 이하 문자, 숫자, @ . + - - _ 만 가능 </td>
        </tr>
        <tr>
            <td>{{ form.password1.label_tag }} {{ form.password1 }}
                <li>다른 개인정보와 유사한 비밀번호는 사용 불가</li>
                <li>비밀번호는 최소 8자 이상</li>
                <li>통상적으로 자주 사용되는 비밀번호는 사용할 수 없음</li>
                <li>숫자로만 이루어진 비밀번호는 사용할 수 없음</li>
            </td>
        </tr>
        <tr>
            <td>{{ form.password2.label_tag }} {{ form.password2 }} 확인을 위해 이전과 동일한 비밀번호를 입력하세요.</td>
        </tr>
        <tr>
            <td>{{ form.email.label_tag }} {{ form.email }}</td>
        </tr>
    </table>
</form> -->
<form>
    <input type="submit" value="회원가입">
</form>
<a href = "{% url 'accounts:login' %}">login 화면으로 이동</a>
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Small Business - Start Bootstrap Template</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'styles.css' %}" rel="stylesheet" type="text/css"/>
        <link href="{% static 'bootstrap.min.css' %}" rel="stylesheet" type="text/css"/>
    </head>
    <body>
        <!-- base.html, navbar.html, footer.html은 공통으로 쓰는 파일이기 때문에 templates 바로 아래에 만든다. -->
        <!-- header와 footer는 어떤 페이지에 접속하든 화면의 상단과 하단에 위치하도록 템플릿화 하는게 효율적 -->
        {% include "navbar.html" %}
        {% block content %}
        {% endblock %}
        {% include "footer.html" %}
    </body>
</html>

templates/footer.html
<!-- Footer-->
<footer class="py-5 bg-dark">
    <div class="container px-4 px-lg-5"><p class="m-0 text-center text-white">Copyright &copy; Your Website 2023</p></div>
</footer>

templates/goods/company_info.html
{% extends 'base.html'%}
{% block content %}
<h1>회사소개 페이지 입니다.</h1>
{% endblock %}

templates/goods/mainpage.html
{% extends 'base.html'%}
{% block content %}
<h1>메인 페이지 입니다.</h1>
{% endblock %}

templates/navbar.html
<!-- a태그 수정할 부분 -->
<!-- <a href="/company/">company info</a> -->
<!-- <a href="/promote/">product</a> -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container px-5">
        <a class="navbar-brand" href="#!">Start Bootstrap</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                <li class="nav-item"><a class="nav-link active" aria-current="page" href="/">Home</a></li>
                <li class="nav-item"><a class="nav-link" href="/company/">Company Info</a></li>
                <li class="nav-item"><a class="nav-link" href="/promote/">Product</a></li>
                {% if user.is_authenticated %}
                <li class="nav-item"><a class="nav-link" href="{% url 'accounts:logout' %}">{{ user.username }} (logout) </a></li>
                {% else %}
                <li class="nav-item"><a class="nav-link" href="{% url 'accounts:login' %}">login</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

templates/promote/comment_form.html
{% extends 'base.html' %}
{% block content %}
<h2> update comment </h2>
<section class="mb-5">
    <div class="card bg-light">
        <div class="card-body">
            <form method="post" class="mb-4" action="{% url 'comment_update' comment.id %}">
                {% csrf_token %}
                <textarea id ="content" name="content" class="form-control" rows="3">{{form.content.value}}</textarea>
                <button type="submit" class="btn btn-primary">submit</button>
            </form>
        </div>
    </div>
</section>
{% endblock %}

templates/promote/content_detail.html
{% extends 'base.html' %}
{% block content %}
<h2>{{ content_list.title }}</h2>
<div>
    {{content_list.pub_date}}<br>
    {{content_list.content}}
</div>
<section class="mb-5">
    <div class="card bg-light">
        <div class="card-body">
            <form method="post" class="mb-4" action="{% url 'comment_create' content_list.id %}">
                {% csrf_token %}
                <textarea id="content" name="content" class="form-control" rows="3" placeholder="답변 내용을 입력해주세요."></textarea>
                <button type="submit" class="btn btn-primary">submit</button>
            </form>
            {% for comment in content_list.comment_set.all %}
            <div class="d-flex">
                <div class="ms-3">
                    <div class="fw-bold">
                        {{comment.author.username}} &nbsp {{comment.create_date}}
                        <!--microsecond가 달라서  comment.create_date 와  comment.modify_date 결과값 항상 다르게 나옴  -->
                        {% if comment.create_date.second != comment.modify_date.second %} 
                        / 수정일자 : {{comment.modify_date}} 
                        {{comment.create_date.hour}}:{{comment.create_date.minute}}:{{comment.create_date.second}}:{{comment.create_date.microsecond}} 
                        {{comment.modify_date.hour}}:{{comment.modify_date.minute}}:{{comment.modify_date.second}}:{{comment.modify_date.microsecond}} 
                        {% endif %}

                        {% if request.user == comment.author %}
                            <a href="{% url 'comment_update' comment.id %}" class="btn btn-sm btn-outline-secondary">수정</a>
                            <a href="{% url 'comment_delete' comment.id %}" class="btn btn-sm btn-outline-secondary">삭제</a>
                        {% endif %}

                    </div>
                    {{comment.content}}
                </div>
            </div>
            <br/>
            {% endfor %}
        </div>
    </div>
</section>
{% endblock %}

templates/promote/content_list.html
{% extends 'base.html'%}
{% load static %}
{% block content %}
<!-- Page Content-->
<!-- promote/views.py에 content_list로 콘텐츠 목록 있는지 검증 -->
{% if content_list %} 
    {% for content in content_list %}
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 align-items-center my-5">
                <div class="col-lg-7"><img class="img-fluid rounded mb-4 mb-lg-0" src="https://dummyimage.com/900x400/dee2e6/6c757d.jpg" alt="..." /></div>                
                <div class="col-lg-5">
                    <!-- n번째 상품 등록, href = 하드코딩 안하고 템플릿문법으로 작성 -->
                    <h1 class="font-weight-light"><a href="{% url 'detail' content.id %}"></a>{{content.title}}</h1>
                    <!-- n번째 상품입니다. 상품 사이즈는 m 입니다, truncatewords:30 로 문자열 30단어만 출력 -->
                    <p>{{content.content | truncatewords:30 }}</p>
                    <a class="btn btn-primary" href="{% url 'detail' content.id %}">상품 상세보기</a>
                </div>
            </div>
        </div>
    {% endfor %}
{% else %}
    <p>content가 없습니다.</p>  
{% endif %}
{% endblock %}